# Generated by Django 3.1.2 on 2020-10-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201028_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRegister',
        ),
    ]
