# Generated by Django 3.1.2 on 2020-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201028_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='Date',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
