# Generated by Django 3.1.3 on 2020-11-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
